# Generated by Django 3.1.2 on 2021-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211105_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug_field',
            field=models.SlugField(default='no_slugs', max_length=100),
        ),
    ]
